- inventories/dev/group_vars/dhcp-dev
That would prevent dnsmasq from leasing addresses to hosts that it doesn't
know their mac addresses
> Explicit dhcp ranges that cover all known hosts

- inventories/group_vars/netapp-dev
- roles/netapp/tasks/cfssl.yaml
- roles/netapp/tasks/core.yaml
- roles/netapp/tasks/kube.yaml
- Create dedicated ipspace and broadcast domain per env
- Add 2nd port on the netapp vlan (Netapp will operate as HA between controllers
and on active-passive between ports on the same controller)
- Even though failover policies are not supported for iscsi services, if an
interface fails it will only be able to migrate in the same ipspcae/broadcast
domain, which now only contain environment specific interfaces
- Deploy the 2nd port for dev environment
> Revised netapp network setup

- inventories/hosts
- roles/cumulus/handlers/main.yaml
- roles/cumulus/tasks/main.yaml
- roles/cumulus/templates/network-interfaces.tmpl
Add a new interfaces template and host specific variables
Add a handler to `sudo ifreload -a` on /etc/network/interfaces change
`DRY_RUN=true make cumulus ARGS="--tags=network"` gives the following differences (mostly fmt):
```
--- before: /etc/network/interfaces                                                                                                                                                                         
+++ after: /home/foivos/go/src/github.com/utilitywarehouse/sys-ansible-k8s-on-prem/"/tmp"/ansible-local-19296DuSkS/tmpeISxGB/network-interfaces.tmpl                                                        
@@ -1,6 +1,5 @@ …
```
> Template cumulus network interfaces

- inventories/group_vars/dhcp-dev
- inventories/group_vars/dhcp-prod
- inventories/group_vars/hosts-prod
- inventories/group_vars/netapp-prod
- roles/cumulus/templates/frr.conf.tmpl
- roles/dhcp/templates/dhcp.conf.tmpl
- add dhcp configuration
- add bgp peers on the new matchbox hosts addresses
- create netapp svm, export policy and volume
> matchbox prod deployment

- roles/cumulus/files/10ssh.rules
Needed since all traffic is natted out before reaching cumulus for the last
time. Specifically it prevented dev-merit from accessing github.com:22
> Allow forwarding traffic from public subnets

- Makefile
The awk check is comparing chars, so it started failing when upgrading to
versions >= 2.10
> Remove ansible version check from Makefile

- Makefile
- cumulus.yaml
- dhcp_exp.yaml
- inventories/group_vars/dhcp-dev
- inventories/group_vars/dhcp-exp
- inventories/group_vars/dhcp-prod
- inventories/group_vars/hosts-dev
- inventories/group_vars/hosts-exp
- inventories/group_vars/hosts-prod
- roles/cumulus/templates/frr.conf.tmpl
- roles/dhcp/tasks/main.yaml
- roles/dhcp/templates/dhcp.conf.tmpl
- roles/dhcp/templates/dhcp.service.tmpl
- Change jinja2 template to support optional blocks, instead of defining empty
vars
- Add separate dhcp service for exp cluster on vlan 1188
> Refactor dhcp config template and add exp dhcp service

- roles/cumulus/templates/frr.conf.tmpl
The fallback route will have metric 254. It makes this route only used
when the NAT boxes are not available ( if we are rebooting / rebuilding
the whole environment). As soon as the NAT boxes become  available they will
provide default routes with metric 200 (learned via iBGP), which will
have priority over this static route (254).
Also filtering the default route learned from merit house as they are
not in use.
> Adding the fallback default route for DEV / filtering default route

- roles/cumulus/templates/frr.conf.tmpl
The fallback route will have metric 254. It makes this route only used
when the NAT boxes are not available ( if we are rebooting / rebuilding
the whole environment). As soon as the NAT boxes become  available they will
provide default routes with metric 200 (learned via iBGP), which will
have priority over this static route (254).
Also filtering the default route learned from merit house as they are
not in use.
> Adding the fallback default route for PROD / filtering default route

- inventories/group_vars/hosts-dev
This adds 3 masters and 15 workers in dev-merit.
We will need to run:
- `make dhcp-dev` to update dhcp daemon config
- `make cumulus` to update the bgp peers for dev vrf
> Add new nodes to dev-merit

- inventories/group_vars/hosts-dev
Already applied to allow me to boot the new nodes in dev-merit, but forgot to raise it
> dev: serve ipxe.efi to m710x nodes on boot

- roles/cumulus/templates/network-interfaces.tmpl
1- Adding a new stand-alone interface swp25
2- Creating a MLAG with port swp25 and clid 25 too.
3- Adding the new MLAG interface, to the bridge interface.
> Adding new interface config for moonshot3

- inventories/group_vars/hosts-dev
Moving masters and etcds away from moonshot-0 into 1,2 and 3 to improve
redundancy. Shoving a few moonshot-0 workers to moonshot-1 to make room.
> dev-merit: spread nodes on all moonshots

- Makefile
- inventories/group_vars/netapp-dev
- inventories/group_vars/netapp-exp
- roles/netapp/tasks/kube.yaml
- Create a policy with strict limits to see the impact on the behaviour on nodes
- Tag and exclude from prod runs, so we can still run netapp-prod target
> dev: Create a policy group to be used by kube pvcs

- roles/cumulus/templates/network-interfaces.tmpl
Fixing the problems with MLAG introduced in 4.3.0:
https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-43/Whats-New/rn/
https://support.mellanox.com/s/case/5001T00001YdbYeQAJ
After upgrading to Cumulus Linux, MLAG ports might remain down with clagctl and net show clag reporting bridge-priority-mismatch.
To work around this issue, run the sudo ifreload -a command on both peers, or configure bridge-bridgeprio to be the same value as mstpcl-treeprio on the bridge interface in the /etc/network/interfaces file, then run sudo ifreload -a.
> Bug (new behaviour) introduced on Cumulus 4.3.0

- Makefile
- inventories/group_vars/netapp-prod
This ensures iops limits between prod loads and should be used as a good
practice against bad actors. Haven't seen any complaints after using it on dev
for a couple of weeks.
> prod-merit: Create a policy group to be used by kube pvcs

- inventories/group_vars/hosts-dev
- inventories/group_vars/hosts-prod
This updates hosts to scale prod-merit workers.
We need to apply both dhcp and cumulus targets (to update the bgp peers for
prod)
> Scale prod-merit to 18 workers

- inventories/group_vars/hosts-dev
Needs to run `make dhcp-dev` to apply the changes to our dhcp servers and
`make culumus-dev-prod` to apply the frr changes and update BGP peers for
cumulus servers on dev vrf.
> Scale dev-merit workers

- inventories/group_vars/cumulus
Needs to be applied for both exp and prod environment:
`make cumulus-exp ARGS="--tags=node-exporter"`
`make cumulus-dev-prod ARGS="--tags=node-exporter"`
> Update node-exporter version running on cumulus

- Makefile
Change the make targets behaviour so that they result in a dry run unless suffixed with -execute. That should replace setting DRY_RUN env variable with a more explicit way of knowing whem `make` is actively going to change remote config.
> Create explicit -execute make targets instead of setting DRY_RUN

- roles/netapp/tasks/cfssl.yaml
This will match the configuration we get from trident for all PVCs and will fix our metrics/alerts for almost full volumes.
> Do not reserve space for CFSSL volumes

- roles/cumulus/tasks/main.yaml
- roles/dhcp/tasks/main.yaml
Temporary workaround for the failing sudo apt update commands on Cumulus instances
> Comment out Cumulus apt update commands
